<?php

/**
 * @file
 */


/**
 * Implements hook_form_FORM_ID_alter().
 */
function green_user_form_user_profile_form_alter(&$form, &$form_state) {
  // Merge the main profile form to the user form
  if (($type = profile2_get_types('main')) && $type->userCategory) {
    if (empty($form_state['profiles'])) {
      $profile = profile2_load_by_user($form['#user'], 'main');
      if (empty($profile)) {
        $profile = profile_create(array('type' => 'main', 'uid' => $form['#user']->uid));
      }
      $form_state['profiles'][$profile->type] = $profile;
    }
    profile2_attach_form($form, $form_state);
  }
}


/**
 * Implements hook_menu_alter().
 */
function green_user_menu_alter(&$items) {
  $items['user/%user/edit/main']['access callback'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter() for the user edit form.
 */
function  green_user_form_user_main_form_alter(&$form, &$form_state) {

}


/**
 * Implements hook_user_view_alter().
 */
function green_user_user_view_alter(&$build) {
  global $user; 
 
  // Convertion user name string to url with pathauto
  if (module_exists('pathauto')) {
      module_load_include('inc', 'pathauto', 'pathauto');
      $name =  pathauto_cleanstring($user->name);        
  }
  // Deleting history information
  if (isset($build['summary'])) {
      unset($build['summary']);
  }
   $build['alimentation'] = array(
    '#type' => 'link',
    '#title' => t('Alimentation'),
    '#href' => 'alimentation/'.$name,
    '#weight' => -20,
  );
   
  $build['travel'] = array(
    '#type' => 'link',
    '#title' => t('Déplacements'),
    '#href' => 'travel/'.$name,
    '#weight' => -15,
  );
  
  //$score = module_invoke_all('green_user_score',$node);

 // $build['text'] = array(
  //    '#markup' => '<p class="dashboard-text"> Score : ' . $score . '</p>',
 //     '#weight' => -10,
  //    );
  
  $build['user_picture']['#title'] = t('user picture');
   
  $build['email'] = array(
    '#type' => 'user_profile_item',
    '#title' => t('Email'),
    '#markup' => $user->mail,
    '#weight' => -9,
  );  

}

/**
 * Implémente hook_menu_local_tasks_alter().
 */
function green_user_menu_local_tasks_alter(&$data, $router_item, $root_path) {
 // Add a menu local task to user page
 global $user;
 if ($root_path == 'user/%') {  
    // Clean the user name string into a url
    //module_load_include('module', 'pathauto', 'pathauto');
    if (module_exists('pathauto')) {
         module_load_include('inc', 'pathauto', 'pathauto');
         $name =  pathauto_cleanstring($user->name);        
    } 
   
    $item = menu_get_item('alimentation/'.$name);
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_task',
        '#link' => $item,
      );
    }
    
  }
}




