<?php
/**
 * @file
 * green_alimentation.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function green_alimentation_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-alimentation-field_achat_commerce_quitable'
  $field_instances['node-alimentation-field_achat_commerce_quitable'] = array(
    'bundle' => 'alimentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_achat_commerce_quitable',
    'label' => 'Achat commerce équitable',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 32,
    ),
  );

  // Exported field_instance: 'node-alimentation-field_achat_de_produit_frais'
  $field_instances['node-alimentation-field_achat_de_produit_frais'] = array(
    'bundle' => 'alimentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_achat_de_produit_frais',
    'label' => 'Achat de produits frais',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 33,
    ),
  );

  // Exported field_instance: 'node-alimentation-field_achat_produits_locaux'
  $field_instances['node-alimentation-field_achat_produits_locaux'] = array(
    'bundle' => 'alimentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_achat_produits_locaux',
    'label' => 'Achat produits locaux',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 34,
    ),
  );

  // Exported field_instance: 'node-alimentation-field_conso_poissons'
  $field_instances['node-alimentation-field_conso_poissons'] = array(
    'bundle' => 'alimentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Combien de fois consomez-vous du poisson dans la semaine ?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_conso_poissons',
    'label' => 'Fréquence de consommation de poissons par semaine',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 31,
    ),
  );

  // Exported field_instance: 'node-alimentation-field_j_utilise_des_paniers_ou_d'
  $field_instances['node-alimentation-field_j_utilise_des_paniers_ou_d'] = array(
    'bundle' => 'alimentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_j_utilise_des_paniers_ou_d',
    'label' => 'J’utilise des paniers ou des sacs  réutilisables',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 36,
    ),
  );

  // Exported field_instance: 'node-alimentation-field_je_bois_l_eau_du_robinet'
  $field_instances['node-alimentation-field_je_bois_l_eau_du_robinet'] = array(
    'bundle' => 'alimentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_je_bois_l_eau_du_robinet',
    'label' => 'Je bois l’eau du robinet',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 35,
    ),
  );

  // Exported field_instance: 'node-alimentation-field_type_de_regime'
  $field_instances['node-alimentation-field_type_de_regime'] = array(
    'bundle' => 'alimentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_type_de_regime',
    'label' => 'Type de régime',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => -4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Achat commerce équitable');
  t('Achat de produits frais');
  t('Achat produits locaux');
  t('Combien de fois consomez-vous du poisson dans la semaine ?');
  t('Fréquence de consommation de poissons par semaine');
  t('Je bois l’eau du robinet');
  t('J’utilise des paniers ou des sacs  réutilisables');
  t('Type de régime');

  return $field_instances;
}
